### ISSUE TITLE
Error in running default model parameters

### ISSUE THREAD

**Issue by DuyTran16** [malekokour1/DosePredict#1]
I was able to use this app a few months ago, but it's not able to run from the parameter values entered today.  I received an "Error: the model build step failed." when using the default values.  I am running the app via `shiny::runGitHub('malekokour1/DosePredict')`

**Comment by Mutaz94** [comment]
Hi @DuyTran16 it looks like this is mrgsolve issue. Can you update mrgsolve  (`install.packages('mrgsolve')`) to the latest version and run again?

**Comment by DuyTran16** [comment]
@Mutaz94 I currently have the most recent version of [mrgsolve](https://cran.r-project.org/web/packages/mrgsolve/index.html) on CRAN, which is 0.11.1

These are the packages dependencies for DosePredict and their version on my computer.
`library(tidyverse)

tibble(
  Package = names(installed.packages()[, 3]),
  Version = unname(installed.packages()[, 3])
) %>%
  filter(
    Package %in% c(
      "shiny",
      "shinyjs",
      "shinyBS",
      "shinythemes",
      "shinydashboard",
      "mrgsolve",
      "deSolve",
      "magrittr",
      "ggplot2",
      "plotly",
      "PKNCA",
      "data.table",
      "dplyr",
      "RColorBrewer",
      "rmarkdown",
      "knitr",
      "reshape2"
    )
  )`

Package        Version
<chr>          <chr>
  1 data.table     1.14.2
2 deSolve        1.30
3 dplyr          1.0.7
4 ggplot2        3.3.5
5 knitr          1.36
6 magrittr       2.0.1
7 mrgsolve       0.11.1
8 PKNCA          0.9.4
9 plotly         4.10.0
10 RColorBrewer   1.1-2
11 reshape2       1.4.4
12 rmarkdown      2.11
13 shiny          1.7.1
14 shinyBS        0.61
15 shinydashboard 0.7.2
16 shinyjs        2.0.0
17 shinythemes    1.2.0

I am getting a different error message using default values for DosePredict today:

> Error: Must group by variables found in `.data`.
> * Column `amt` is not found.
> * Column `time` is not found.

**Comment by kylebaron** [comment]
@DuyTran16 This is what I got too when I ran; there is some problem with a join it does at some point. if you download the simulated data it has `.x` and `.y` suffixes on the column names. 

<img width="925" alt="Screen Shot 2021-10-22 at 10 48 08 PM" src="https://user-images.githubusercontent.com/16908301/138541348-dbe1bfe9-e55d-43a6-8b12-8526513063bf.png">

**Comment by malekokour** [comment]
Hi Duy,
Apologies for the delayed response as I was ooo. 
I have checked via the webpage (dosePredict.com) and I didn’t get errors when changing parameters values. I wonder if it has to do with using gethub to execute. 
I appreciate Mutaz and Kyle responses as well. 
Best regards,

**Comment by DuyTran16** [comment]
Thank you for fixing the server.  The website hosting the application was down a few weeks ago and I used the  `shiny::runGitHub` to run the app instead but it gave error message.  I am able visit website [dose predict](www.dosePredict.com) now.

**Comment by malekokour** [comment]
You are right, the site was down but we managed to get it up and running. 
Just to mention, in the future if the site goes down, hopefully it doesn’t happen again, you can use the below direct shiny link 

https://mokour.shinyapps.io/DosePredict/

Best regards,
